image:
  file: .gitpod.dockerfile

tasks:
  - init: |
      docker-compose pull
  - command: |
      mysql -e "CREATE DATABASE todos"
      mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';"
      docker-compose up

ports:
  - port: 8000
    onOpen: notify
  - port: 3000
    onOpen: notify